export { AboutSection } from "./components/about-section"
export { DestinationsSection } from "./components/destinations-section"
export { HeroSection } from "./components/hero-section"
export { ServicesSection } from "./components/services-section"
export { TestimonialsSection } from "./components/testimonials-section"
